"""comit

Revision ID: ed1ce36cdebc
Revises: f275f597830d
Create Date: 2026-01-28 23:53:40.470125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1ce36cdebc'
down_revision: Union[str, Sequence[str], None] = 'f275f597830d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
